name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3


    - name: dependencies
      run: exportx=${PWD}; for i in */; do for j in "$i/*/"; do cd ${PWD}/"$j"; make; done; done;
    - name: make
      run: make setup
    - name: make 
      run: make

