name: C/C++ CI

on:
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3


    - name: dependencies
      run: sudo apt install *cap*stone* -y -no-confirm
    - name: make
      run: make setup
    - name: make 
      run: make

