name: C/C++ CI

on:
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3


    - name: dependencies
      run: export x=${PWD}; for i in */; do cd $i; for j in */; do cd $j; make; done; cd ../$i; make; cd $x; done;
    - name: make
      run: make setup
    - name: make 
      run: make

